### ISSUE TITLE
Send back to page we came from after signing in

### ISSUE THREAD

**Issue by hundrex** [LucileDT/boustigraille#107]
It would be great to be send back to the page we were browsing after connecting. Currently we are redirected on the home page by default, which is annoying in many use cases (like when I want to edit one of my recipe but I am not connected, I would like to go back to this page after connecting).

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I have strange behaviors, we need to check it together

**Comment by LucileDT** [comment]
This is still bugged

Scenario:
- go to the login page
- using top menu, go to the recipes list
- using top menu, log in

Expected behavior:
we are redirected to the recipes list

Current behavior:
we are redirected t othe home page

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL this has been fixed, can you please test it too?

**Comment by Yann-BUTSCHER-EIRL** [comment]
It works!
