### ISSUE TITLE
Recipe search bar in meal list form is broken

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/boustigraille#183]
- connect
- create a meal list
- add a recipe
- open the select2 and start typing

Expected behaviour:
results are filtered

Current behaviour:
an error is thrown

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT This bug is not existing on my local env (develop branch).
It seems to only exists in production. As we know for now this is due to a PostgreSql config error.
It would be nice to try and fix this at the next production deployment.

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I think we should have a way to test the PostgreSQL behavior and notify admins with a flashbag when it misses something to work properly. This way, we would easily be able to know there is a problem. Can you do it?

**Comment by Yann-BUTSCHER-EIRL** [comment]
Working on it

**Comment by Yann-BUTSCHER-EIRL** [comment]
The query to execute to fix this is: `CREATE EXTENSION unaccent`

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT @hundrex This is done! Waiting for tests!
