### ISSUE TITLE
Update to Symfony 6

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/boustigraille#189]
- [x] remove deprecations
- [x] update Symfony version

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL can you please test the whole app? I'm not sure we don't have introduced any regressions with this whole thing, especially since the work has been split in like 2 years

**Comment by Yann-BUTSCHER-EIRL** [comment]
The fixtures were deprecated so I updated them (see last commit).
