### ISSUE TITLE
Notifications are created with a duplicate id 

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LucileDT/boustigraille#190]
- reset your database 
  - you need to have the notification table reset at least  
- connect
- send a followMealList notification to a user
- send a followUsernameOnRecipe notification to a user (can be the same, it doesn't matter)

Expected behaviour:
The notifications are created with different id's

Current behaviour:
The notifications are created with the same id so an error is thrown

**Comment by LucileDT** [comment]
The whole notifications and follow requests stack needs a rework, I was definitively too tired to work on it at the time but did it anyways :neutral_face:

**Comment by Yann-BUTSCHER-EIRL** [comment]
Yes. Closing since we will rework them with #207.
