### ISSUE TITLE
Rework the notification and follow system

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LucileDT/boustigraille#207]
- [x] Change the backend mechanisms
  - [x] Search for existing library
  - [x] Redo the entities
  - [x] Redo the controllers and forms
- [x] Keep the existing interfaces but adapt them

**Comment by Yann-BUTSCHER-EIRL** [comment]
You'll find the new database model below:

![image](https://github.com/user-attachments/assets/7ca3aaa7-736b-4e2d-aa3d-e6e0b3febdf9)

**Comment by Yann-BUTSCHER-EIRL** [comment]
This is finish! Hurray!
@LucileDT Can you test it thoroughly please?

**Comment by LucileDT** [comment]
Tested, it seems to work really well, thanks! :+1:

**Comment by LucileDT** [comment]
Merged on develop :tada:
