### ISSUE TITLE
We can see an username that has not been shared by its user in the meal list creation page

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LucileDT/boustigraille#210]
Scenario:
- Add a recipe created by someone who is not sharing its username with you, to you favorite recipes
- Go to the meal list creation page
- Use the select widget to add a recipe to the meal list

Expected behavior:
- The select opens and shows the recipe list
  - You can only see the name of the user that have shared their username with you

Current behavior:
- The select opens and shows the recipe list
  - You can only see all the usernames (see image below)

![image](https://github.com/user-attachments/assets/a5d20509-40c9-4c90-8ffe-5bc35f673c17)

**Comment by LucileDT** [comment]
🙀

**Comment by Yann-BUTSCHER-EIRL** [comment]
The same bug was happening with the suggested recipes card so I fixed it too.
