### ISSUE TITLE
Username is not visible when not logged in even if the user has choosen to make it public

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/boustigraille#218]
**Scenario:**

- create a user
- make it share its username publicly
- create a new recipe with it
- disconnect and go on the recipe list

**Expected behavior:**

Username is shown on the corresponding recipe

![image](https://github.com/user-attachments/assets/929ba5b1-fd32-4ed5-8650-a567668f192c)

**Current behavior:**

Username is not shown

![image](https://github.com/user-attachments/assets/f1eed559-bd96-4170-a5f7-7fc9c87a2b42)

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT Fixed. Need testing.
